### ISSUE TITLE
video not appearing on web ui

### ISSUE THREAD

**Issue by ITZMETONYSTARK** [aws-samples/amazon-rekognition-video-analyzer#38]
sir,thank you soo much for an such wonderfull project.the problem what i face is that videos are not showing up at webui..i checked the cloudwatch logs for improcessor lambda and it shown an error which i am posting below:


13:15:25
END RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4

13:15:25
REPORT RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Duration: 2029.31 ms Billed Duration: 2100 ms Memory Size: 128 MB Max Memory Used: 53 MB

13:15:26
START RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Version: $LATEST

13:15:26
Expecting property name: line 10 column 2 (char 206): ValueError Traceback (most recent call last): File "/var/task/imageprocessor.py", line 182, in handler return process_image(event, context) File "/var/task/imageprocessor.py", line 48, in process_image config = load_config() File "/var/task/imageprocessor.py", line 24, in load_config return json.loads(conf_json) File "/usr/l
Expecting property name: line 10 column 2 (char 206): ValueError
Traceback (most recent call last):
File "/var/task/imageprocessor.py", line 182, in handler
return process_image(event, context)
File "/var/task/imageprocessor.py", line 48, in process_image
config = load_config()
File "/var/task/imageprocessor.py", line 24, in load_config
return json.loads(conf_json)
File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 10 column 2 (char 206)


13:15:26
END RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4

13:15:26
REPORT RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Duration: 546.06 ms Billed Duration: 600 ms Memory Size: 128 MB Max Memory Used: 53 MB

13:15:27
START RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Version: $LATEST

13:15:27
Expecting property name: line 10 column 2 (char 206): ValueError Traceback (most recent call last): File "/var/task/imageprocessor.py", line 182, in handler return process_image(event, context) File "/var/task/imageprocessor.py", line 48, in process_image config = load_config() File "/var/task/imageprocessor.py", line 24, in load_config return json.loads(conf_json) File "/usr/l

13:15:27
END RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4

13:15:27
REPORT RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Duration: 157.44 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 53 MB

13:15:28
START RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Version: $LATEST

13:15:28
Expecting property name: line 10 column 2 (char 206): ValueError Traceback (most recent call last): File "/var/task/imageprocessor.py", line 182, in handler return process_image(event, context) File "/var/task/imageprocessor.py", line 48, in process_image config = load_config() File "/var/task/imageprocessor.py", line 24, in load_config return json.loads(conf_json) File "/usr/l

13:15:28
END RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4

13:15:28
REPORT RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Duration: 184.41 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 54 MB

13:15:30
START RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Version: $LATEST

13:15:30
Expecting property name: line 10 column 2 (char 206): ValueError Traceback (most recent call last): File "/var/task/imageprocessor.py", line 182, in handler return process_image(event, context) File "/var/task/imageprocessor.py", line 48, in process_image config = load_config() File "/var/task/imageprocessor.py", line 24, in load_config return json.loads(conf_json) File "/usr/l

13:15:30
END RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4

13:15:30
REPORT RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Duration: 176.75 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 54 MB

13:15:34
START RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4 Version: $LATEST

13:15:34
Expecting property name: line 10 column 2 (char 206): ValueError Traceback (most recent call last): File "/var/task/imageprocessor.py", line 182, in handler return process_image(event, context) File "/var/task/imageprocessor.py", line 48, in process_image config = load_config() File "/var/task/imageprocessor.py", line 24, in load_config return json.loads(conf_json) File "/usr/l

13:15:34
END RequestId: 0b6d13ac-f996-4f68-95ce-66f345f9bbc4

**Comment by sumanghosh12** [comment]
@moanany
