### ISSUE TITLE
any one help?

### ISSUE THREAD

**Issue by jackylee1** [aws-samples/amazon-rekognition-video-analyzer#39]
pynt deploylambda
[ build.pyc - Starting task "deploylambda" ]
Checking if S3 Bucket 'anbanglee2' exists...
Uploading function 'framefetcher' to 'src/lambda_framefetcher.zip'
[ build.pyc - Error in task "deploylambda" ]
[ build.pyc - Aborting build ]
Traceback (most recent call last):
  File "/Users/anbanglee/anaconda2/bin/pynt", line 11, in <module>
    sys.exit(main())
  File "/Users/anbanglee/anaconda2/lib/python2.7/site-packages/pynt/_pynt.py", line 298, in main
    build(sys.argv[1:])
  File "/Users/anbanglee/anaconda2/lib/python2.7/site-packages/pynt/_pynt.py", line 59, in build
    _run_from_task_names(module,args.tasks)
  File "/Users/anbanglee/anaconda2/lib/python2.7/site-packages/pynt/_pynt.py", line 109, in _run_from_task_names
    _run(module, logger, task, completed_tasks, True, args, kwargs)
  File "/Users/anbanglee/anaconda2/lib/python2.7/site-packages/pynt/_pynt.py", line 180, in _run
    task(*(args or []),**(kwargs or {}))
  File "/Users/anbanglee/anaconda2/lib/python2.7/site-packages/pynt/_pynt.py", line 245, in __call__
    self.func.__call__(*args,**kwargs)
  File "build.py", line 143, in deploylambda
    s3_client.upload_fileobj(data, src_s3_bucket_name, s3_keys[function])
  File "/Users/anbanglee/anaconda2/lib/python2.7/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/Users/anbanglee/.local/lib/python2.7/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/Users/anbanglee/.local/lib/python2.7/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by jackylee1** [comment]
？？

**Comment by moanany** [comment]
Hello,

It's likely an issue with your system time being off.

Check out this thread:
https://github.com/aws/aws-cli/issues/602

Excerpt:

> Just had this happening to me and was a result of my system time being off by too much even though it did not report that. Ran ntpdate against pool.ntp.org and fixed this problem for me.

Hope that helps,
Moataz
