### ISSUE TITLE
Stuck in the createstack

### ISSUE THREAD

**Issue by mtogat** [aws-samples/amazon-rekognition-video-analyzer#43]
Well, I have done everything I can possible think off, if anyone can help I really appreciate.
 pynt createstack
[ build.pyc - Starting task "createstack" ]
[ build.pyc - Error in task "createstack" ]
[ build.pyc - Aborting build ]
Traceback (most recent call last):
  File "/usr/bin/pynt", line 11, in <module>
    load_entry_point('pynt==0.8.2', 'console_scripts', 'pynt')()
  File "/usr/lib/python2.7/dist-packages/pynt/_pynt.py", line 298, in main
    build(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pynt/_pynt.py", line 59, in build
    _run_from_task_names(module,args.tasks)
  File "/usr/lib/python2.7/dist-packages/pynt/_pynt.py", line 109, in _run_from_task_names
    _run(module, logger, task, completed_tasks, True, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/pynt/_pynt.py", line 180, in _run
    task(*(args or []),**(kwargs or {}))
  File "/usr/lib/python2.7/dist-packages/pynt/_pynt.py", line 245, in __call__
    self.func.__call__(*args,**kwargs)
  File "build.py", line 156, in createstack
    stack_name = global_params_dict["StackName"]

**Comment by mtogat** [comment]
thanks, what happened is that I misunderstood the variable. Stackname, fixed and it worked.
