### ISSUE TITLE
Final step videocapture

### ISSUE THREAD

**Issue by A1a3el** [aws-samples/amazon-rekognition-video-analyzer#50]
i've made it to last step `pynt videocaptureip["<your-ip-cam-mjpeg-url>"]`,<capture-rate>but im running with some issues,im hoping someone can tell me if im missing something when executing the last part
### **via ip camera:**
i keep getting and error type,it connects for a second and then it dies....the message that im getting is thi:

`[ build.py - Starting task "videocaptureip" ]
Capturing from 'http://192.168.1.78:8081' at a rate of 1 every 20 frames...
Traceback (most recent call last):
  File "video_cap_ipcam.py", line 141, in <module>
    main()
  File "video_cap_ipcam.py", line 105, in main
    bytes += stream.read(16384*2)
TypeError: can only concatenate str (not "bytes") to str
[ build.py - Completed task "videocaptureip" `

### **Via web cam:**

when i run it it seems to work because i keep getting 

`{'ShardId': 'shardId-000000000000', 'SequenceNumber': '49597758662347182382206873118270965332318602047252332546', 'ResponseMetadata': {'RequestId': 'c2c360dd-dd9c-3541-976f-38d97fe5e46b', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'c2c360dd-dd9c-3541-976f-38d97fe5e46b', 'x-amz-id-2': 'WoUPxGafWCb/ZB3aakhu/0/F8jCK9Hzbylv22q4UZHrK0pQ4XlWF9stz0GoBX7jbX9UUWDxuZmXXvsxZGuRD2rpdV38z8HFWPhw+Jg7iSVk=', 'date': 'Fri, 19 Jul 2019 23:44:04 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '110'}, 'RetryAttempts': 0}}`

but after i execute this step, nothing appears on the dashed area in the Web UI(waited a couple minutes)

importan note: i  did changed/convert some files to python3 since im running the project on it 
files changed:
- imageprocessor.py
- video_cap.py
- video_cap_ipcam.py
- build.py
also changed the cPickle lib to pickle

Pd: pynt stackstatus is a green light 
`[ build.py - Starting task "stackstatus" ]   
Stack 'video-analyzer-stack' has the status 'CREATE_COMPLETE'
[ build.py - Completed task "stackstatus" ]
`
Any help on this is gladly appreciated

**Comment by Moriuks** [comment]
update:
it did run on the computers camera without a problem...but im  still getting `TypeError: can only concatenate str` whenever i tried and external camara(im using an app for a ip camera).

**Comment by sumanghosh12** [comment]
@Moriuks - I am facing the same issue. Were you able to over come the issue? 

@moanany - Please help!!!

**Comment by Moriuks** [comment]
Hellooo,
i ended up changing the architecture to [link](https://aws.amazon.com/blogs/machine-learning/easily-perform-facial-analysis-on-live-feeds-by-creating-a-serverless-video-analytics-environment-with-amazon-rekognition-video-and-amazon-kinesis-video-streams/), there is also a github repo where you can view the architecture i used.
Alternative: 
The problem was that you are running python3 with some parts of python 2 at some bytes level but i dont really remember wich part of the code .

**Comment by sumanghosh12** [comment]
Thank you @Moriuks .

In the article it states that the stack will be created in us-east-1. 
But the template is in us-west-2. 

![image](https://user-images.githubusercontent.com/31139148/76676017-cce03680-6595-11ea-96f6-b79d999313a2.png)


I am getting this error. Any idea why?
Lambda was unable to encrypt your environment variables because the KMS access was denied. Please check your KMS permissions. KMS Exception: AccessDeniedException KMS Message: User:
